stages:
  - check
  - deploy

zap-check:
  image: ghcr.io/zaproxy/zaproxy
  stage: check
  allow_failure: true
  variables:
    ZAP_TARGET: "https://case-manager.qpartners.tech/"
  before_script:
    - mkdir -p /zap/wrk
  script:
    - zap-baseline.py -t $ZAP_TARGET -g gen.conf -I -r baseline.html
    - cp /zap/wrk/baseline.html baseline.html
  artifacts:
    when: always
    paths:
      - baseline.html

deploy:
  only:
    - main
  stage: deploy
  script:
    - cp $ENV "$(pwd)/.env"
      - docker login registry.fibo.cloud -p ${REGISTRY_FIBO_PASSWORD} -u ${REGISTRY_FIBO_USERNAME}
      - docker build -t registry.fibo.cloud/adb/case-manager/dashboard .
      - docker push registry.fibo.cloud/adb/case-manager/dashboard
      - docker ps --quiet --filter="name=dashboard" | xargs --no-run-if-empty docker rm -f
      - docker run -dt -p 3000:80 --restart always --name dashboard registry.fibo.cloud/adb/case-manager/dashboard
  tags:
    - cloudmn-casemanager
